-- Modern
local modern = {
  ["chat"] = {
    ["global"] = {
      ["custombg"] = "1",
      ["border"] = "0.1,0.1,0.1,0.5",
      ["background"] = "0.1,0.1,0.1,0.2",
    },
    ["right"] = {
      ["enable"] = "1",
      ["alwaysshow"] = "1",
    },
  },
  ["global"] = {
    ["font_unit"] = "Interface\\AddOns\\pfUI\\fonts\\Myriad-Pro.ttf",
    ["font_size"] = "11",
    ["font_unit_size"] = "11",
  },
  ["panel"] = {
    ["left"] = {
      ["left"] = "exp",
    },
    ["xp"] = {
      ["dont_overlap"] = "1",
      ["xp_always"] = "1",
      ["xp_mode"] = "HORIZONTAL",
      ["xp_position"] = "TOP",
      ["xp_anchor"] = "pfActionBarLeft",
      ["xp_color"] = "0.6,0.6,0.6,1",
      ["rest_color"] = "0.4,0.4,0.4,0.5",
      ["xp_height"] = "4",
      ["rep_always"] = "1",
      ["rep_mode"] = "HORIZONTAL",
      ["rep_position"] = "TOP",
      ["rep_anchor"] = "pfActionBarRight",
      ["rep_height"] = "4",
      ["rep_display"] = "FLEX",
    },
  },
  ["unitframes"] = {
    ["custom"] = "2",
    ["custompbgcolor"] = "0.3,0.1,0.1,1",
    ["custombgcolor"] = "0.3,0.1,0.1,1",
    ["ragecolor"] = "0.6,0.2,0.2,1",
    ["energycolor"] = "0.6,0.4,0.2,1",
    ["manacolor"] = "0.2,0.2,0.4,1",
    ["focuscolor"] = "0.6,0.4,0.2,1",
    ["customcolor"] = "0.1,0.1,0.1,1",

    ["grouptarget"] = {
      ["bartexture"] = "Interface\\AddOns\\pfUI\\img\\bar_gradient",
      ["pbartexture"] = "Interface\\AddOns\\pfUI\\img\\bar_gradient",
    },
    ["ptarget"] = {
      ["bartexture"] = "Interface\\AddOns\\pfUI\\img\\bar_gradient",
      ["pbartexture"] = "Interface\\AddOns\\pfUI\\img\\bar_gradient",
    },
    ["target"] = {
      ["bartexture"] = "Interface\\AddOns\\pfUI\\img\\bar_gradient",
      ["pbartexture"] = "Interface\\AddOns\\pfUI\\img\\bar_gradient",
      ["txthpleft"] = "healthdyn",
      ["pspace"] = "1",
      ["txtpowerleft"] = "powerdyn",
      ["height"] = "22",
      ["buffs"] = "TOPRIGHT",
      ["txthpright"] = "unitrev",
      ["buffsize"] = "16",
      ["portrait"] = "right",
      ["width"] = "160",
    },
    ["ttarget"] = {
      ["bartexture"] = "Interface\\AddOns\\pfUI\\img\\bar_gradient",
      ["pbartexture"] = "Interface\\AddOns\\pfUI\\img\\bar_gradient",
      ["pspace"] = "1",
      ["height"] = "7",
      ["portrait"] = "off",
    },
    ["pet"] = {
      ["bartexture"] = "Interface\\AddOns\\pfUI\\img\\bar_gradient",
      ["pbartexture"] = "Interface\\AddOns\\pfUI\\img\\bar_gradient",
      ["pspace"] = "1",
      ["pheight"] = "3",
      ["txtpowercenter"] = "healthdyn",
      ["height"] = "7",
      ["buffs"] = "BOTTOMLEFT",
      ["portrait"] = "off",
      ["debuffs"] = "BOTTOMRIGHT",
    },
    ["player"] = {
      ["txtpowerright"] = "powerdyn",
      ["bartexture"] = "Interface\\AddOns\\pfUI\\img\\bar_gradient",
      ["pbartexture"] = "Interface\\AddOns\\pfUI\\img\\bar_gradient",
      ["pspace"] = "1",
      ["debuffs"] = "TOPRIGHT",
      ["portrait"] = "left",
      ["buffsize"] = "16",
      ["width"] = "160",
      ["height"] = "22",
      ["showPVP"] = "1",
    },
    ["customfullhp"] = "1",
    ["focustarget"] = {
      ["bartexture"] = "Interface\\AddOns\\pfUI\\img\\bar_gradient",
      ["pbartexture"] = "Interface\\AddOns\\pfUI\\img\\bar_gradient",
    },
    ["customfade"] = "1",
    ["group"] = {
      ["bartexture"] = "Interface\\AddOns\\pfUI\\img\\bar_gradient",
      ["pbartexture"] = "Interface\\AddOns\\pfUI\\img\\bar_gradient",
    },
    ["raid"] = {
      ["indicator_pos"] = "TOPRIGHT",
      ["verticalbar"] = "1",
      ["txthpleft"] = "none",
      ["defcolor"] = "0",
      ["customfade"] = "1",
      ["focuscolor"] = "0.6,0.4,0.2,1",
      ["raidpadding"] = "5",
      ["txthpcenter"] = "namehealthbreak",
      ["ragecolor"] = "0.6,0.2,0.2,1",
      ["bartexture"] = "Interface\\AddOns\\pfUI\\img\\bar_gradient",
      ["pbartexture"] = "Interface\\AddOns\\pfUI\\img\\bar_gradient",
      ["glowaggro"] = "0",
      ["height"] = "35",
      ["txthpright"] = "none",
      ["customcolor"] = "0.1,0.1,0.1,1",
      ["width"] = "40.7",
      ["manacolor"] = "0.2,0.2,0.4,1",
      ["energycolor"] = "0.6,0.4,0.2,1",
      ["customfullhp"] = "1",
      ["custom"] = "2",
    },
    ["focus"] = {
      ["bartexture"] = "Interface\\AddOns\\pfUI\\img\\bar_gradient",
      ["pbartexture"] = "Interface\\AddOns\\pfUI\\img\\bar_gradient",
    },
    ["tttarget"] = {
      ["bartexture"] = "Interface\\AddOns\\pfUI\\img\\bar_gradient",
      ["pbartexture"] = "Interface\\AddOns\\pfUI\\img\\bar_gradient",
    },
    ["grouppet"] = {
      ["bartexture"] = "Interface\\AddOns\\pfUI\\img\\bar_gradient",
      ["pbartexture"] = "Interface\\AddOns\\pfUI\\img\\bar_gradient",
    },
  },
  ["appearance"] = {
    ["castbar"] = {
      ["texture"] = "Interface\\AddOns\\pfUI\\img\\bar_gradient",
    },
    ["minimap"] = {
      ["coordsloc"] = "topleft",
    },
    ["border"] = {
      ["color"] = "0.1,0.1,0.1,1",
      ["bags"] = "3",
      ["chat"] = "3",
      ["default"] = "2",
    },
  },
  ["tooltip"] = {
    ["statusbar"] = {
      ["texture"] = "Interface\\AddOns\\pfUI\\img\\bar_gradient",
    },
  },
  ["castbar"] = {
    ["player"] = {
      ["showrank"] = "1",
      ["height"] = "12",
      ["showlag"] = "1",
      ["showicon"] = "1",
    },
    ["target"] = {
      ["height"] = "12",
      ["showicon"] = "1",
    },
  },
  ["abuttons"] = {
    ["enable"] = "1",
    ["hideincombat"] = "0",
  },
  ["nameplates"] = {
    ["heighthealth"] = "10",
    ["healthtexture"] = "Interface\\AddOns\\pfUI\\img\\bar_gradient",
    ["health"] = {
      ["offset"] = "10",
    },
  },
  ["bars"] = {
    ["bar4"] = {
      ["enable"] = "0",
    },
    ["bar11"] = {
      ["background"] = "0",
      ["spacing"] = "3",
    },
    ["bar5"] = {
      ["formfactor"] = "12 x 1",
      ["buttons"] = "6",
    },
    ["bar3"] = {
      ["formfactor"] = "12 x 1",
      ["buttons"] = "6",
    },
  }
}

-- Legacy
local legacy = {
  ["chat"] = {
    ["right"] = {
      ["enable"] = "1",
    },
  },
}

-- Slim
local slim = {
  ["panel"] = {
    ["use_unitfonts"] = "1",
  },
  ["tooltip"] = {
    ["position"] = "bottom",
  },
  ["appearance"] = {
    ["infight"] = {
      ["screen"] = "0",
      ["common"] = "1",
    },
    ["border"] = {
      ["color"] = "0,0,0,1",
      ["bags"] = "3",
      ["panels"] = "1",
      ["unitframes"] = "1",
      ["default"] = "1",
      ["background"] = "0.1,0.1,0.1,0.8",
      ["chat"] = "2",
      ["actionbars"] = "1",
    },
  },
  ["buffbar"] = {
    ["pdebuff"] = {
      ["enable"] = "1",
      ["height"] = "14",
    },
    ["pbuff"] = {
      ["enable"] = "1",
      ["height"] = "14",
    },
    ["tdebuff"] = {
      ["enable"] = "1",
      ["height"] = "14",
    },
  },
  ["chat"] = {
    ["global"] = {
      ["tabmouse"] = "1",
      ["tabdock"] = "0",
      ["border"] = "0,0,0,0",
      ["background"] = "0,0,0,0.3",
      ["custombg"] = "1",
    },
    ["text"] = {
      ["outline"] = "0",
    },
    ["left"] = {
      ["height"] = "160",
      ["width"] = "405",
    },
    ["right"] = {
      ["enable"] = "1",
      ["height"] = "160",
      ["width"] = "405",
    },
  },
  ["bars"] = {
    ["background"] = "0",
    ["icon_size"] = "22",
  },
  ["version"] = "3.3.0",
  ["nameplates"] = {
    ["use_unitfonts"] = "1",
  },
  ["unitframes"] = {
    ["target"] = {
      ["buffsize"] = "14",
      ["pheight"] = "6",
      ["height"] = "35",
      ["panchor"] = "TOPLEFT",
      ["pspace"] = "-1",
      ["width"] = "225",
    },
    ["pet"] = {
      ["debuffs"] = "top",
      ["pheight"] = "6",
      ["pspace"] = "-1",
      ["width"] = "125",
    },
    ["player"] = {
      ["buffsize"] = "14",
      ["txthpleft"] = "powerdyn",
      ["height"] = "35",
      ["showPVP"] = "1",
      ["panchor"] = "TOPRIGHT",
      ["pspace"] = "-1",
      ["width"] = "225",
      ["pheight"] = "6",
    },
    ["custombgcolor"] = "0.5,0.2,0.2,1",
    ["focus"] = {
      ["pheight"] = "6",
    },
    ["raid"] = {
      ["height"] = "24",
      ["width"] = "48",
    },
    ["custombg"] = "1",
    ["customcolor"] = "0.15,0.15,0.15,1",
    ["custom"] = "1",
    ["ttarget"] = {
      ["portrait"] = "off",
      ["pheight"] = "6",
      ["height"] = "16",
      ["pspace"] = "-1",
      ["width"] = "125",
    },
    ["tttarget"] = {
      ["portrait"] = "off",
      ["pheight"] = "6",
      ["height"] = "16",
      ["pspace"] = "-1",
      ["width"] = "125",
    },
    ["ptarget"] = {
      ["portrait"] = "off",
      ["pheight"] = "-1",
      ["height"] = "8",
      ["pspace"] = "-1",
      ["width"] = "125",
    },
  },
}

-- Adapta
local adapta = {
  ["appearance"] = {
    ["infight"] = {
      ["screen"] = "1",
      ["common"] = "0",
    },
    ["border"] = {
      ["color"] = "0,0,0,1",
      ["unitframes"] = "1",
      ["background"] = "0.05,0.15,0.15,0.75",
      ["actionbars"] = "4",
    },
  },
  ["unitframes"] = {
    ["target"] = {
      ["portrait"] = "off",
      ["height"] = "35",
      ["panchor"] = "TOPLEFT",
      ["pspace"] = "-1",
      ["width"] = "225",
      ["pheight"] = "6",
    },
    ["pet"] = {
      ["debuffs"] = "top",
      ["portrait"] = "off",
      ["pspace"] = "-1",
      ["width"] = "125",
      ["pheight"] = "6",
    },
    ["player"] = {
      ["portrait"] = "off",
      ["txthpleft"] = "powerdyn",
      ["height"] = "35",
      ["showPVP"] = "1",
      ["panchor"] = "TOPRIGHT",
      ["pspace"] = "-1",
      ["width"] = "225",
      ["pheight"] = "6",
    },
    ["focus"] = {
      ["portrait"] = "off",
      ["pheight"] = "6",
    },
    ["ttarget"] = {
      ["portrait"] = "off",
      ["height"] = "16",
      ["pspace"] = "-1",
      ["width"] = "125",
      ["pheight"] = "6",
    },
    ["tttarget"] = {
      ["portrait"] = "off",
      ["height"] = "16",
      ["pspace"] = "-1",
      ["width"] = "125",
      ["pheight"] = "6",
    },
    ["ptarget"] = {
      ["portrait"] = "off",
      ["height"] = "8",
      ["pspace"] = "-1",
      ["width"] = "125",
      ["pheight"] = "-1",
    },
    ["customcolor"] = "0.1,0.2,0.2,1",
    ["custombg"] = "1",
    ["custom"] = "1",
  },
  ["bars"] = {
    ["icon_size"] = "17",
    ["right"] = {
      ["formfactor"] = "4 x 3",
    },
    ["bottomright"] = {
      ["formfactor"] = "4 x 3",
    },
  },
  ["chat"] = {
    ["global"] = {
      ["tabmouse"] = "1",
      ["tabdock"] = "0",
      ["border"] = "0,0,0,1",
      ["custombg"] = "1",
      ["background"] = "0.15,0.25,0.25,0.3",
    },
    ["text"] = {
      ["outline"] = "0",
    },
    ["left"] = {
      ["height"] = "161",
      ["width"] = "400",
    },
    ["right"] = {
      ["enable"] = "1",
      ["height"] = "161",
      ["width"] = "400",
    },
  },
}

-- Minimal
local minimal = {
  ["totems"] = {
    ["direction"] = "VERTICAL",
  },
  ["disabled"] = {
    ["totems"] = "0",
    ["pixelperfect"] = "0",
    ["skin_Merchant"] = "0",
    ["skin_Options - Sound"] = "0",
    ["skin_KeyBindings"] = "0",
    ["unlock"] = "0",
    ["roll"] = "0",
    ["feigndeath"] = "0",
    ["target"] = "0",
    ["map"] = "0",
    ["skin_Trainer"] = "0",
    ["skin_Profession"] = "0",
    ["tooltip"] = "0",
    ["skin_Talents"] = "0",
    ["hdgraphic"] = "0",
    ["player"] = "0",
    ["updatenotify"] = "0",
    ["hunterbar"] = "0",
    ["skin_Color Picker"] = "0",
    ["targettargettarget"] = "0",
    ["mapreveal"] = "0",
    ["bags"] = "1",
    ["superwow"] = "0",
    ["chat"] = "0",
    ["autoshift"] = "0",
    ["turtle-wow"] = "0",
    ["focus"] = "0",
    ["thirdparty-vanilla"] = "0",
    ["raid"] = "0",
    ["combopoints"] = "0",
    ["skin_Petition"] = "0",
    ["skin_Guild Registrar"] = "0",
    ["skin_Stack Split"] = "0",
    ["skin_Help"] = "0",
    ["cooldown"] = "0",
    ["targettarget"] = "0",
    ["sellvalue"] = "0",
    ["skin_Opacity"] = "0",
    ["hoverbind"] = "0",
    ["actionbar"] = "0",
    ["custom"] = "0",
    ["skin_Tutorial"] = "0",
    ["skin_Options - Interface"] = "0",
    ["mirrortimers"] = "0",
    ["afkcam"] = "0",
    ["share"] = "0",
    ["skin_Pet Stable Master"] = "0",
    ["chatcopy"] = "0",
    ["autovendor"] = "0",
    ["bubbles"] = "0",
    ["loot"] = "0",
    ["skin_Books"] = "0",
    ["easteregg"] = "0",
    ["skin_Battlefield Minimap"] = "0",
    ["skin_Guild Tabard"] = "0",
    ["uf_tukui"] = "0",
    ["skin"] = "0",
    ["skin_Trade"] = "0",
    ["skin_Options - Video"] = "0",
    ["itemclick"] = "0",
    ["castbar"] = "0",
    ["infight"] = "0",
    ["unusable"] = "0",
    ["xpbar"] = "0",
    ["addons"] = "0",
    ["skin_Friends"] = "0",
    ["pet"] = "0",
    ["mouseover"] = "0",
    ["socialmod"] = "0",
    ["macrotweak"] = "0",
    ["thirdparty"] = "0",
    ["whisperproxy"] = "0",
    ["skin_Coin Pickup"] = "0",
    ["gm"] = "0",
    ["mapcolors"] = "0",
    ["eqcompare"] = "0",
    ["skin_Macro"] = "0",
    ["energytick"] = "0",
    ["buffwatch"] = "0",
    ["addoncompat"] = "0",
    ["minimap"] = "0",
    ["group"] = "0",
    ["farmmode"] = "0",
    ["nameplates"] = "0",
    ["addonbuttons"] = "0",
    ["skin_Auctionhouse"] = "0",
    ["skin_Battlefield"] = "0",
    ["buff"] = "0",
    ["skin_Character"] = "0",
    ["skin_Battlefield Score"] = "0",
    ["skin_Dress Up Frame"] = "0",
    ["skin_Game Menu"] = "0",
    ["skin_Quest Timer"] = "0",
    ["panel"] = "0",
    ["skin_Flightmaster"] = "0",
    ["questitem"] = "0",
    ["screenshot"] = "0",
    ["skin_Inspect"] = "0",
    ["skin_Spellbook"] = "0",
    ["pettarget"] = "0",
    ["skin_Mailbox"] = "0",
    ["skin_GM Survey"] = "0",
    ["skin_Gossip and Quest"] = "0",
    ["firstrun"] = "0",
    ["skin_Readycheck"] = "0",
    ["skin_Popup Dialogs"] = "0",
    ["skin_Tooltips"] = "0",
    ["tracking"] = "0",
    ["skin_Quest Log"] = "0",
  },
  ["unitframes"] = {
    ["pet"] = {
      ["pspace"] = "-1",
      ["pheight"] = "6",
      ["width"] = "125",
    },
    ["ptarget"] = {
      ["pspace"] = "-1",
      ["height"] = "8",
      ["portrait"] = "off",
      ["width"] = "125",
    },
    ["customcolor"] = "0.15,0.15,0.15,1",
    ["target"] = {
      ["panchor"] = "TOPLEFT",
      ["pspace"] = "-1",
      ["width"] = "225",
      ["buffsize"] = "14",
      ["height"] = "35",
      ["pheight"] = "6",
    },
    ["ttarget"] = {
      ["pspace"] = "-1",
      ["pheight"] = "6",
      ["height"] = "16",
      ["portrait"] = "off",
      ["width"] = "125",
    },
    ["custom"] = "1",
    ["player"] = {
      ["txthpleft"] = "powerdyn",
      ["txthprightoffy"] = "-4",
      ["panchor"] = "TOPRIGHT",
      ["pspace"] = "-1",
      ["txthpleftoffy"] = "-6",
      ["squareaggro"] = "1",
      ["width"] = "180",
      ["squarepos"] = "CENTER",
      ["squaresize"] = "22",
      ["height"] = "25",
      ["showPVP"] = "1",
      ["buffsize"] = "14",
    },
    ["abbrevnum"] = "0",
    ["group"] = {
      ["txthpleftoffy"] = "-6",
      ["txthprightoffy"] = "-6",
      ["txtpowerright"] = "powerdyn",
      ["pheight"] = "11",
      ["txthpleftoffx"] = "06",
      ["poffy"] = "-3",
      ["height"] = "24",
      ["width"] = "130",
    },
    ["custombgcolor"] = "0.5,0.2,0.2,1",
    ["focus"] = {
      ["width"] = "90",
      ["height"] = "20",
      ["pheight"] = "6",
    },
    ["raid"] = {
      ["height"] = "24",
      ["width"] = "48",
    },
    ["tttarget"] = {
      ["pspace"] = "-1",
      ["pheight"] = "6",
      ["height"] = "16",
      ["portrait"] = "off",
      ["width"] = "125",
    },
    ["custombg"] = "1",
  },
  ["buffbar"] = {
    ["pdebuff"] = {
      ["width"] = "100",
      ["height"] = "14",
      ["enable"] = "1",
    },
    ["pbuff"] = {
      ["width"] = "80",
      ["height"] = "14",
      ["enable"] = "1",
    },
    ["tdebuff"] = {
      ["width"] = "136",
      ["height"] = "14",
      ["enable"] = "1",
    },
  },
  ["thirdparty"] = {
    ["shagudps"] = {
      ["skin"] = "1",
      ["dock"] = "1",
    },
    ["twt"] = {
      ["skin"] = "1",
    },
    ["showmeter"] = "1",
    ["chatbg"] = "0",
  },
  ["appearance"] = {
    ["infight"] = {
      ["common"] = "1",
    },
    ["worldmap"] = {
      ["mapexploration"] = "1",
      ["mapreveal"] = "1",
    },
    ["bags"] = {
      ["icon_size"] = "28",
      ["movable"] = "1",
    },
    ["border"] = {
      ["color"] = "0,0,0,1",
      ["bags"] = "3",
      ["panels"] = "1",
      ["unitframes"] = "1",
      ["default"] = "1",
      ["actionbars"] = "1",
      ["background"] = "0.1,0.1,0.1,0.7",
      ["chat"] = "2",
    },
    ["minimap"] = {
      ["size"] = "200",
      ["mouseoverzone"] = "1",
    },
  },
  ["tooltip"] = {
    ["position"] = "cursor",
  },
  ["global"] = {
    ["profile"] = "Minimal",
  },
  ["screenshot"] = {
    ["levelup"] = "1",
    ["loot"] = "4",
  },
  ["panel"] = {
    ["other"] = {
      ["minimap"] = "none",
    },
    ["right"] = {
      ["left"] = "bagspace",
    },
    ["micro"] = {
      ["enable"] = "1",
    },
    ["use_unitfonts"] = "1",
    ["xp"] = {
      ["xp_always"] = "1",
      ["xp_width"] = "740",
      ["xp_anchor"] = "pfActionBarMain",
      ["xp_mode"] = "HORIZONTAL",
      ["xp_height"] = "8",
      ["xp_position"] = "BOTTOM",
    },
    ["left"] = {
      ["center"] = "fps",
      ["left"] = "zone",
    },
  },
  ["version"] = "5.4.11",
  ["position"] = {
    ["pfFocus"] = {
      ["xpos"] = 118,
      ["parent"] = "UIParent",
      ["ypos"] = 214,
      ["anchor"] = "BOTTOM",
    },
    ["pfActionBarLeft"] = {
      ["xpos"] = -278,
      ["parent"] = "UIParent",
      ["ypos"] = 16,
      ["anchor"] = "BOTTOM",
    },
    ["pfBank"] = {
      ["xpos"] = 115,
      ["anchor"] = "TOPLEFT",
      ["ypos"] = -557,
      ["parent"] = "UIParent",
    },
    ["pfLootRollFrame4"] = {
      ["xpos"] = -325,
      ["anchor"] = "RIGHT",
      ["ypos"] = -143,
      ["parent"] = "UIParent",
    },
    ["pfCombo3"] = {
      ["xpos"] = -524,
      ["anchor"] = "BOTTOMRIGHT",
      ["ypos"] = 144,
      ["parent"] = "UIParent",
    },
    ["pfActionBarMain"] = {
      ["xpos"] = 0,
      ["parent"] = "UIParent",
      ["ypos"] = 11,
      ["anchor"] = "BOTTOM",
    },
    ["pfRaidCluster"] = {
      ["xpos"] = 0,
      ["parent"] = "UIParent",
      ["ypos"] = 250,
      ["anchor"] = "BOTTOMLEFT",
    },
    ["pfGroup1"] = {
      ["xpos"] = 182,
      ["anchor"] = "TOPLEFT",
      ["ypos"] = -14,
      ["parent"] = "UIParent",
    },
    ["pfTargetDebuffBar"] = {
      ["xpos"] = 230,
      ["parent"] = "UIParent",
      ["ypos"] = 168,
      ["anchor"] = "BOTTOM",
    },
    ["pfGroup2"] = {
      ["xpos"] = 182,
      ["anchor"] = "TOPLEFT",
      ["ypos"] = -80,
      ["parent"] = "UIParent",
    },
    ["pfChatLeft"] = {
      ["xpos"] = -1,
      ["parent"] = "UIParent",
      ["ypos"] = -1,
      ["anchor"] = "BOTTOMLEFT",
    },
    ["pfActionBarRight"] = {
      ["xpos"] = 277,
      ["parent"] = "UIParent",
      ["ypos"] = 17,
      ["anchor"] = "BOTTOM",
    },
    ["pfLootRollFrame1"] = {
      ["xpos"] = -325,
      ["anchor"] = "RIGHT",
      ["ypos"] = -27,
      ["parent"] = "UIParent",
    },
    ["pfPanelMicroButton"] = {
      ["xpos"] = 0,
      ["parent"] = "UIParent",
      ["ypos"] = 0,
      ["anchor"] = "TOPLEFT",
    },
    ["pfLootRollFrame3"] = {
      ["xpos"] = -326,
      ["anchor"] = "RIGHT",
      ["ypos"] = -104,
      ["parent"] = "UIParent",
    },
    ["pfChatInputBox"] = {
      ["xpos"] = 2,
      ["parent"] = "UIParent",
      ["ypos"] = 224,
      ["anchor"] = "BOTTOMLEFT",
    },
    ["pfActionBarTop"] = {
      ["xpos"] = 0,
      ["parent"] = "UIParent",
      ["ypos"] = 46,
      ["anchor"] = "BOTTOM",
    },
    ["pfBag"] = {
      ["xpos"] = 1209,
      ["anchor"] = "TOPLEFT",
      ["ypos"] = -481,
      ["parent"] = "UIParent",
    },
    ["pfLootRollFrame2"] = {
      ["xpos"] = -325,
      ["anchor"] = "RIGHT",
      ["ypos"] = -65,
      ["parent"] = "UIParent",
    },
    ["pfPlayerDebuffBar"] = {
      ["xpos"] = -122,
      ["parent"] = "UIParent",
      ["ypos"] = 197,
      ["anchor"] = "BOTTOM",
    },
    ["pfGroup3"] = {
      ["xpos"] = 182,
      ["anchor"] = "TOPLEFT",
      ["ypos"] = -144,
      ["parent"] = "UIParent",
    },
    ["WorldMapFrame"] = {
      ["xpos"] = 0,
      ["scale"] = 0.69999998807907,
      ["ypos"] = 0,
      ["alpha"] = 1,
      ["anchor"] = "CENTER",
    },
    ["pfExperienceBar"] = {
      ["xpos"] = 0,
      ["anchor"] = "BOTTOM",
      ["ypos"] = 0,
      ["parent"] = "UIParent",
    },
    ["pfTotems"] = {
      ["xpos"] = 523,
      ["parent"] = "UIParent",
      ["ypos"] = 115,
      ["scale"] = 1,
      ["anchor"] = "BOTTOMLEFT",
    },
    ["pfFocusCastbar"] = {
      ["xpos"] = 119,
      ["parent"] = "UIParent",
      ["ypos"] = 194,
      ["anchor"] = "BOTTOM",
    },
    ["pfActionBarStances"] = {
      ["xpos"] = 470,
      ["parent"] = "UIParent",
      ["ypos"] = 111,
      ["anchor"] = "BOTTOMLEFT",
    },
    ["pfTargetTargetTarget"] = {
      ["scale"] = 1.1,
    },
    ["pfPlayer"] = {
      ["xpos"] = 588,
      ["parent"] = "UIParent",
      ["ypos"] = -770,
      ["anchor"] = "TOPLEFT",
    },
    ["pfChatRight"] = {
      ["xpos"] = -1,
      ["parent"] = "UIParent",
      ["ypos"] = 0,
      ["anchor"] = "BOTTOMRIGHT",
    },
    ["pfActionBarPet"] = {
      ["xpos"] = -197,
      ["parent"] = "UIParent",
      ["ypos"] = 86,
      ["anchor"] = "BOTTOM",
    },
    ["pfGroup4"] = {
      ["xpos"] = 182,
      ["anchor"] = "TOPLEFT",
      ["ypos"] = -209,
      ["parent"] = "UIParent",
    },
    ["pfFocusTarget"] = {
      ["xpos"] = 123,
      ["parent"] = "UIParent",
      ["ypos"] = 240,
      ["anchor"] = "BOTTOM",
    },
    ["QuestTimerFrame"] = {
      ["xpos"] = -42,
      ["anchor"] = "RIGHT",
      ["ypos"] = 125,
      ["parent"] = "UIParent",
    },
  },
  ["nameplates"] = {
    ["use_unitfonts"] = "1",
  },
  ["bars"] = {
    ["bar3"] = {
      ["icon_size"] = "27",
      ["showempty"] = "0",
      ["background"] = "0",
    },
    ["bar9"] = {
      ["icon_size"] = "22",
      ["background"] = "0",
    },
    ["count_color"] = "0,0.9,1,1",
    ["bar11"] = {
      ["icon_size"] = "28",
      ["background"] = "0",
    },
    ["font"] = "Interface\\AddOns\\pfUI\\fonts\\Homespun.ttf",
    ["bar7"] = {
      ["icon_size"] = "22",
      ["background"] = "0",
    },
    ["bar6"] = {
      ["icon_size"] = "28",
      ["showempty"] = "0",
      ["background"] = "0",
    },
    ["bar10"] = {
      ["icon_size"] = "22",
      ["background"] = "0",
    },
    ["bar4"] = {
      ["icon_size"] = "28",
      ["showempty"] = "0",
      ["background"] = "0",
    },
    ["bar1"] = {
      ["icon_size"] = "28",
      ["showempty"] = "0",
      ["background"] = "0",
    },
    ["bar2"] = {
      ["icon_size"] = "28",
      ["showempty"] = "0",
      ["background"] = "0",
    },
    ["bar5"] = {
      ["icon_size"] = "27",
      ["showempty"] = "0",
      ["background"] = "0",
    },
    ["bar8"] = {
      ["icon_size"] = "22",
      ["background"] = "0",
    },
    ["bar12"] = {
      ["icon_size"] = "22",
      ["showempty"] = "0",
      ["background"] = "0",
    },
    ["bind_size"] = "13",
  },
  ["chat"] = {
    ["global"] = {
      ["tabmouse"] = "1",
      ["border"] = "0,0,0,0",
      ["frameshadow"] = "0",
      ["background"] = "0,0,0,0",
      ["custombg"] = "1",
    },
    ["text"] = {
      ["outline"] = "0",
      ["time"] = "1",
    },
    ["left"] = {
      ["height"] = "220",
      ["width"] = "460",
    },
    ["right"] = {
      ["enable"] = "1",
      ["height"] = "220",
      ["width"] = "460",
    },
  },
}



-- xCenter
local xCenter = {
  ["disabled"] = {
    ["totems"] = "0",
    ["pixelperfect"] = "0",
    ["skin_Merchant"] = "0",
    ["skin_Options - Sound"] = "0",
    ["skin_Options - Video"] = "0",
    ["unlock"] = "0",
    ["loot"] = "0",
    ["feigndeath"] = "0",
    ["chatcopy"] = "0",
    ["map"] = "0",
    ["skin_Trainer"] = "0",
    ["skin_Profession"] = "0",
    ["tooltip"] = "0",
    ["skin_Talents"] = "0",
    ["hdgraphic"] = "0",
    ["player"] = "0",
    ["updatenotify"] = "0",
    ["hunterbar"] = "0",
    ["skin_Color Picker"] = "0",
    ["targettargettarget"] = "0",
    ["mapreveal"] = "0",
    ["bags"] = "1",
    ["superwow"] = "0",
    ["chat"] = "0",
    ["autoshift"] = "0",
    ["turtle-wow"] = "0",
    ["focus"] = "0",
    ["thirdparty-vanilla"] = "0",
    ["raid"] = "0",
    ["skin_Quest Log"] = "0",
    ["skin_Petition"] = "0",
    ["skin_Guild Registrar"] = "0",
    ["skin_Stack Split"] = "0",
    ["skin_Help"] = "0",
    ["tracking"] = "0",
    ["targettarget"] = "0",
    ["sellvalue"] = "0",
    ["skin_Tutorial"] = "0",
    ["skin_Popup Dialogs"] = "0",
    ["skin_Readycheck"] = "0",
    ["firstrun"] = "0",
    ["skin_Opacity"] = "0",
    ["skin_Options - Interface"] = "0",
    ["mirrortimers"] = "0",
    ["skin_Gossip and Quest"] = "0",
    ["share"] = "0",
    ["skin_Pet Stable Master"] = "0",
    ["skin_GM Survey"] = "0",
    ["autovendor"] = "0",
    ["bubbles"] = "0",
    ["skin_Mailbox"] = "0",
    ["skin_Books"] = "0",
    ["easteregg"] = "0",
    ["skin_Battlefield Minimap"] = "0",
    ["skin_Guild Tabard"] = "0",
    ["uf_tukui"] = "0",
    ["skin"] = "0",
    ["skin_Trade"] = "0",
    ["skin_Spellbook"] = "0",
    ["skin_Inspect"] = "0",
    ["screenshot"] = "0",
    ["infight"] = "0",
    ["questitem"] = "0",
    ["xpbar"] = "0",
    ["addons"] = "0",
    ["skin_Flightmaster"] = "0",
    ["mouseover"] = "0",
    ["unusable"] = "0",
    ["socialmod"] = "0",
    ["macrotweak"] = "0",
    ["skin_Game Menu"] = "0",
    ["whisperproxy"] = "0",
    ["skin_Dress Up Frame"] = "0",
    ["mapcolors"] = "0",
    ["gm"] = "0",
    ["eqcompare"] = "0",
    ["skin_Character"] = "0",
    ["buff"] = "0",
    ["skin_Battlefield"] = "0",
    ["skin_Auctionhouse"] = "0",
    ["addonbuttons"] = "0",
    ["group"] = "0",
    ["farmmode"] = "0",
    ["nameplates"] = "0",
    ["minimap"] = "0",
    ["addoncompat"] = "0",
    ["buffwatch"] = "0",
    ["energytick"] = "0",
    ["skin_Macro"] = "0",
    ["skin_Battlefield Score"] = "0",
    ["skin_Coin Pickup"] = "0",
    ["thirdparty"] = "0",
    ["skin_Quest Timer"] = "0",
    ["panel"] = "0",
    ["pet"] = "0",
    ["skin_Friends"] = "0",
    ["hoverbind"] = "0",
    ["itemclick"] = "0",
    ["skin_KeyBindings"] = "0",
    ["pettarget"] = "0",
    ["roll"] = "0",
    ["target"] = "0",
    ["afkcam"] = "0",
    ["custom"] = "0",
    ["actionbar"] = "0",
    ["castbar"] = "0",
    ["skin_Tooltips"] = "0",
    ["cooldown"] = "0",
    ["combopoints"] = "0",
  },
  ["chat"] = {
    ["global"] = {
      ["custombg"] = "1",
      ["tabmouse"] = "1",
      ["border"] = "0,0,0,0",
      ["frameshadow"] = "0",
      ["background"] = "0,0,0,0",
    },
    ["text"] = {
      ["outline"] = "0",
      ["time"] = "1",
      ["input_width"] = "460",
      ["input_height"] = "16",
    },
    ["left"] = {
      ["height"] = "220",
      ["width"] = "460",
    },
    ["right"] = {
      ["enable"] = "1",
      ["height"] = "220",
      ["width"] = "460",
    },
  },
  ["buffs"] = {
    ["textinside"] = "1",
    ["size"] = "32",
  },
  ["panel"] = {
    ["other"] = {
      ["minimap"] = "none",
    },
    ["right"] = {
      ["left"] = "bagspace",
    },
    ["micro"] = {
      ["enable"] = "1",
    },
    ["use_unitfonts"] = "1",
    ["left"] = {
      ["center"] = "fps",
      ["left"] = "exp",
    },
    ["xp"] = {
      ["xp_always"] = "1",
      ["xp_anchor"] = "pfActionBarMain",
      ["xp_mode"] = "HORIZONTAL",
      ["xp_height"] = "8",
      ["xp_position"] = "BOTTOM",
      ["xp_width"] = "740",
    },
  },
  ["unitframes"] = {
    ["player"] = {
      ["indicator_pos"] = "RIGHT",
      ["txthpleft"] = "powerdyn",
      ["squareaggro"] = "1",
      ["panchor"] = "TOPRIGHT",
      ["pspace"] = "-1",
      ["txthpleftoffy"] = "-12",
      ["buffsize"] = "14",
      ["debuffs"] = "off",
      ["squaresize"] = "22",
      ["height"] = "25",
      ["buffs"] = "off",
      ["buff_indicator"] = "1",
      ["showPVP"] = "1",
      ["width"] = "180",
      ["squarepos"] = "CENTER",
      ["txthprightoffy"] = "-12",
    },
    ["ptarget"] = {
      ["pspace"] = "-1",
      ["portrait"] = "off",
      ["height"] = "8",
      ["width"] = "125",
    },
    ["target"] = {
      ["panchor"] = "TOPLEFT",
      ["pspace"] = "-1",
      ["pheight"] = "6",
      ["width"] = "225",
      ["buffsize"] = "14",
      ["height"] = "35",
    },
    ["ttarget"] = {
      ["pspace"] = "-1",
      ["pheight"] = "6",
      ["portrait"] = "off",
      ["height"] = "16",
      ["width"] = "125",
    },
    ["custombg"] = "1",
    ["pet"] = {
      ["pspace"] = "-1",
      ["pheight"] = "6",
      ["width"] = "125",
    },
    ["abbrevnum"] = "0",
    ["group"] = {
      ["txtpowerright"] = "powerdyn",
      ["txthpleftoffy"] = "-6",
      ["pheight"] = "11",
      ["height"] = "24",
      ["txthpleftoffx"] = "06",
      ["poffy"] = "-3",
      ["width"] = "130",
      ["txthprightoffy"] = "-6",
    },
    ["custombgcolor"] = "0.5,0.2,0.2,1",
    ["raid"] = {
      ["raidlayout"] = "4x10",
      ["height"] = "24",
      ["width"] = "48",
    },
    ["focus"] = {
      ["pheight"] = "6",
      ["width"] = "90",
      ["height"] = "20",
    },
    ["tttarget"] = {
      ["pspace"] = "-1",
      ["pheight"] = "6",
      ["portrait"] = "off",
      ["height"] = "16",
      ["width"] = "125",
    },
    ["customcolor"] = "0.15,0.15,0.15,1",
    ["custom"] = "1",
  },
  ["appearance"] = {
    ["infight"] = {
      ["common"] = "1",
    },
    ["worldmap"] = {
      ["mapreveal"] = "1",
      ["mapexploration"] = "1",
    },
    ["bags"] = {
      ["icon_size"] = "28",
      ["movable"] = "1",
    },
    ["border"] = {
      ["color"] = "0,0,0,1",
      ["bags"] = "2",
      ["panels"] = "1",
      ["unitframes"] = "1",
      ["default"] = "1",
      ["background"] = "0.1,0.1,0.1,0.7",
      ["chat"] = "2",
      ["actionbars"] = "1",
    },
    ["minimap"] = {
      ["mouseoverzone"] = "1",
      ["size"] = "220",
      ["coordsloc"] = "topright",
    },
  },
  ["tooltip"] = {
    ["position"] = "cursor",
  },
  ["thirdparty"] = {
    ["chatbg"] = "0",
    ["shagudps"] = {
      ["dock"] = "1",
      ["skin"] = "1",
    },
    ["twt"] = {
      ["skin"] = "1",
    },
    ["showmeter"] = "1",
  },
  ["screenshot"] = {
    ["levelup"] = "1",
    ["loot"] = "4",
  },
  ["abuttons"] = {
    ["rowsize"] = "10",
    ["hideincombat"] = "0",
    ["position"] = "top",
  },
  ["buffbar"] = {
    ["pdebuff"] = {
      ["width"] = "100",
      ["height"] = "14",
      ["enable"] = "1",
    },
    ["pbuff"] = {
      ["width"] = "80",
      ["height"] = "14",
      ["enable"] = "1",
    },
    ["tdebuff"] = {
      ["width"] = "136",
      ["height"] = "14",
      ["enable"] = "1",
    },
  },
  ["version"] = "5.4.11",
  ["position"] = {
    ["QuestTimerFrame"] = {
      ["xpos"] = -432,
      ["parent"] = "UIParent",
      ["ypos"] = -131,
      ["anchor"] = "TOPRIGHT",
    },
    ["pfActionBarLeft"] = {
      ["xpos"] = -154,
      ["anchor"] = "BOTTOM",
      ["ypos"] = 4,
      ["parent"] = "UIParent",
    },
    ["pfBank"] = {
      ["xpos"] = 115,
      ["parent"] = "UIParent",
      ["ypos"] = -557,
      ["anchor"] = "TOPLEFT",
    },
    ["pfTarget"] = {
      ["xpos"] = 236,
      ["parent"] = "UIParent",
      ["ypos"] = 185,
      ["anchor"] = "BOTTOM",
    },
    ["pfActionBarPet"] = {
      ["xpos"] = 14,
      ["anchor"] = "BOTTOM",
      ["ypos"] = 237,
      ["parent"] = "UIParent",
    },
    ["pfBuffFrame"] = {
      ["xpos"] = -4,
      ["parent"] = "UIParent",
      ["ypos"] = -2,
      ["anchor"] = "TOPRIGHT",
    },
    ["pfPlayer"] = {
      ["xpos"] = 464,
      ["anchor"] = "BOTTOMLEFT",
      ["ypos"] = 185,
      ["parent"] = "UIParent",
    },
    ["pfRaidCluster"] = {
      ["xpos"] = 0,
      ["anchor"] = "LEFT",
      ["ypos"] = 0,
      ["parent"] = "UIParent",
    },
    ["pfGroup1"] = {
      ["xpos"] = 211,
      ["parent"] = "UIParent",
      ["ypos"] = 170,
      ["anchor"] = "LEFT",
    },
    ["pfTargetDebuffBar"] = {
      ["xpos"] = 281,
      ["anchor"] = "BOTTOM",
      ["ypos"] = 228,
      ["parent"] = "UIParent",
    },
    ["pfGroup2"] = {
      ["xpos"] = 211,
      ["parent"] = "UIParent",
      ["ypos"] = 100,
      ["anchor"] = "LEFT",
    },
    ["pfChatLeft"] = {
      ["xpos"] = -1,
      ["anchor"] = "BOTTOMLEFT",
      ["ypos"] = -1,
      ["parent"] = "UIParent",
    },
    ["pfActionBarRight"] = {
      ["xpos"] = 240,
      ["anchor"] = "BOTTOM",
      ["ypos"] = 15,
      ["parent"] = "UIParent",
    },
    ["pfLootRollFrame1"] = {
      ["xpos"] = -119,
      ["parent"] = "UIParent",
      ["ypos"] = 343,
      ["anchor"] = "BOTTOMRIGHT",
    },
    ["pfPanelMicroButton"] = {
      ["xpos"] = 0,
      ["anchor"] = "BOTTOMRIGHT",
      ["ypos"] = 220,
      ["parent"] = "UIParent",
    },
    ["pfLootRollFrame3"] = {
      ["xpos"] = -119,
      ["parent"] = "UIParent",
      ["ypos"] = 273,
      ["anchor"] = "BOTTOMRIGHT",
    },
    ["pfTotems"] = {
      ["xpos"] = 449,
      ["scale"] = 1,
      ["ypos"] = -83,
      ["anchor"] = "LEFT",
      ["parent"] = "UIParent",
    },
    ["pfTargetTarget"] = {
      ["xpos"] = 278,
      ["parent"] = "UIParent",
      ["ypos"] = 138,
      ["anchor"] = "BOTTOM",
    },
    ["pfActionBarTop"] = {
      ["xpos"] = 464,
      ["anchor"] = "BOTTOMLEFT",
      ["ypos"] = 20,
      ["parent"] = "UIParent",
    },
    ["pfPet"] = {
      ["xpos"] = -133,
      ["parent"] = "UIParent",
      ["ypos"] = 249,
      ["anchor"] = "BOTTOM",
    },
    ["pfBag"] = {
      ["xpos"] = 1209,
      ["parent"] = "UIParent",
      ["ypos"] = -481,
      ["anchor"] = "TOPLEFT",
    },
    ["pfLootRollFrame2"] = {
      ["xpos"] = -119,
      ["parent"] = "UIParent",
      ["ypos"] = 308,
      ["anchor"] = "BOTTOMRIGHT",
    },
    ["pfPlayerDebuffBar"] = {
      ["xpos"] = -246,
      ["anchor"] = "BOTTOM",
      ["ypos"] = 224,
      ["parent"] = "UIParent",
    },
    ["pfGroup4"] = {
      ["xpos"] = 211,
      ["parent"] = "UIParent",
      ["ypos"] = -40,
      ["anchor"] = "LEFT",
    },
    ["pfGroup3"] = {
      ["xpos"] = 211,
      ["parent"] = "UIParent",
      ["ypos"] = 30,
      ["anchor"] = "LEFT",
    },
    ["pfLootRollFrame4"] = {
      ["xpos"] = -119,
      ["parent"] = "UIParent",
      ["ypos"] = 238,
      ["anchor"] = "BOTTOMRIGHT",
    },
    ["WorldMapFrame"] = {
      ["xpos"] = 0,
      ["scale"] = 0.69999998807907,
      ["ypos"] = 0,
      ["alpha"] = 1,
      ["anchor"] = "CENTER",
    },
    ["pfExperienceBar"] = {
      ["xpos"] = 0,
      ["parent"] = "UIParent",
      ["ypos"] = 0,
      ["anchor"] = "BOTTOM",
    },
    ["pfFocus"] = {
      ["xpos"] = 138,
      ["parent"] = "UIParent",
      ["ypos"] = 274,
      ["anchor"] = "BOTTOM",
    },
    ["pfUITracking"] = {
      ["xpos"] = -100,
      ["parent"] = "UIParent",
      ["ypos"] = 130,
      ["anchor"] = "BOTTOM",
    },
    ["pfMinimap"] = {
      ["xpos"] = 0,
      ["anchor"] = "BOTTOM",
      ["ypos"] = 10,
      ["parent"] = "UIParent",
    },
    ["pfTargetTargetTarget"] = {
      ["xpos"] = -445,
      ["parent"] = "UIParent",
      ["ypos"] = 96,
      ["scale"] = 1.1,
      ["anchor"] = "BOTTOMRIGHT",
    },
    ["pfDurability"] = {
      ["xpos"] = 207,
      ["parent"] = "UIParent",
      ["ypos"] = -131,
      ["anchor"] = "TOP",
    },
    ["pfChatRight"] = {
      ["xpos"] = -1,
      ["anchor"] = "BOTTOMRIGHT",
      ["ypos"] = 0,
      ["parent"] = "UIParent",
    },
    ["pfActionBarMain"] = {
      ["xpos"] = 464,
      ["anchor"] = "BOTTOMLEFT",
      ["ypos"] = 94,
      ["parent"] = "UIParent",
    },
    ["pfActionBarStances"] = {
      ["xpos"] = -179,
      ["anchor"] = "BOTTOM",
      ["ypos"] = 239,
      ["parent"] = "UIParent",
    },
    ["pfFocusTarget"] = {
      ["xpos"] = 164,
      ["parent"] = "UIParent",
      ["ypos"] = 144,
      ["anchor"] = "BOTTOM",
    },
    ["pfChatInputBox"] = {
      ["xpos"] = 2,
      ["anchor"] = "BOTTOMLEFT",
      ["ypos"] = 224,
      ["parent"] = "UIParent",
    },
  },
  ["nameplates"] = {
    ["use_unitfonts"] = "1",
  },
  ["bars"] = {
    ["bar9"] = {
      ["icon_size"] = "22",
      ["background"] = "0",
    },
    ["count_color"] = "0,0.9,1,1",
    ["bar11"] = {
      ["icon_size"] = "27",
      ["autohide"] = "1",
      ["background"] = "0",
    },
    ["font"] = "Interface\\AddOns\\pfUI\\fonts\\Homespun.ttf",
    ["bar7"] = {
      ["icon_size"] = "22",
      ["background"] = "0",
    },
    ["bar6"] = {
      ["icon_size"] = "27",
      ["autohide"] = "1",
      ["background"] = "0",
      ["formfactor"] = "6 x 2",
    },
    ["bar10"] = {
      ["icon_size"] = "22",
      ["background"] = "0",
    },
    ["bind_size"] = "13",
    ["bar12"] = {
      ["icon_size"] = "27",
      ["showempty"] = "0",
      ["background"] = "0",
      ["formfactor"] = "5 x 2",
    },
    ["bar2"] = {
      ["icon_size"] = "28",
      ["showempty"] = "0",
      ["background"] = "0",
    },
    ["bar3"] = {
      ["icon_size"] = "30",
      ["spacing"] = "6",
      ["autohide"] = "1",
      ["background"] = "0",
    },
    ["bar5"] = {
      ["icon_size"] = "30",
      ["spacing"] = "6",
      ["background"] = "0",
      ["formfactor"] = "2 x 6",
    },
    ["bar8"] = {
      ["icon_size"] = "22",
      ["background"] = "0",
    },
    ["bar1"] = {
      ["icon_size"] = "27",
      ["background"] = "0",
      ["formfactor"] = "6 x 2",
    },
    ["bar4"] = {
      ["hide_combat"] = "0",
      ["icon_size"] = "36",
      ["showempty"] = "0",
      ["autohide"] = "1",
      ["background"] = "0",
    },
  },
}

-- assign profiles to userdata
pfUI_profiles["Modern"] = modern
pfUI_profiles["Legacy"] = legacy
pfUI_profiles["Adapta"] = adapta
pfUI_profiles["Slim"] = slim
pfUI_profiles["Minimal"] = minimal
pfUI_profiles["xCenter"] = xCenter

-- overwrite core profiles in userdata
local profile_loader = CreateFrame("Frame")
profile_loader:RegisterEvent("VARIABLES_LOADED")
profile_loader:SetScript("OnEvent", function()
  pfUI_profiles["Modern"] = modern
  pfUI_profiles["Legacy"] = legacy
  pfUI_profiles["Adapta"] = adapta
  pfUI_profiles["Slim"] = slim
  pfUI_profiles["Minimal"] = minimal
  pfUI_profiles["xCenter"] = xCenter
  this:UnregisterAllEvents()
end)
